/**
 * Auto-generated by scripts/generate-content-index.js
 * Do not edit. Run `npm run generate-content` to regenerate.
 */

export const projects: string[] = ["ek-directory-regulariser","magee"];

export const documents: Record<string, string[]> = {
  "ek-directory-regulariser": [
    "system-plan"
  ],
  "magee": [
    "measurement-plan",
    "overview"
  ]
};

const loaders: Record<string, () => Promise<{ default: React.ComponentType }>> = {
  "ek-directory-regulariser/system-plan": () => import("./ek-directory-regulariser/system-plan"),
  "magee/measurement-plan": () => import("./magee/measurement-plan"),
  "magee/overview": () => import("./magee/overview"),
};

export async function getDocument(project: string, document: string) {
  const key = `${project}/${document}`;
  const loader = loaders[key];
  if (!loader) return null;
  const mod = await loader();
  return mod.default;
}
